CREATE TABLE IF NOT EXISTS BANK (
    ID                          BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ADDRESS                     VARCHAR(128),
    REGISTRATION_DATE           VARCHAR(128),
    MATERIALS_DELIVERED         BOOLEAN,
    LAST_CARD_ISSUANCE_DAYS     INT,
    APPROVED_APPLICATIONS_NUM   INT,
    ISSUANCE_CARDS_NUM          INT
);