drop table TASK_LOG ;
drop table EMPLOYEE ;

CREATE TABLE EMPLOYEE (
	ID          BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FIO         VARCHAR(128),
	ADDRESS     VARCHAR(128),
	GRADE_ID 	BIGINT,
	IS_ACTIVE   BOOLEAN,
    CONSTRAINT GRADE_ID_FK FOREIGN KEY (GRADE_ID) REFERENCES GRADE (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TASK_LOG (
    ID              BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    EMPLOYEE_ID     BIGINT,
    TASK_TYPE_ID    BIGINT,
    TASK_SET_DATE   TIMESTAMP,
    IS_COMPLETED    BOOLEAN,
    COMMENTARY      VARCHAR(256),
    CONSTRAINT EMPLOYEE_ID_FK FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (ID) ON DELETE CASCADE,
    CONSTRAINT TASK_TYPE_ID_FK FOREIGN KEY (TASK_TYPE_ID) REFERENCES TASK_TYPE (ID) ON DELETE CASCADE
);