CREATE TABLE GEO_POINT_CACHE (
    ID              BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ADDRESS         VARCHAR(256),
    LATITUDE        REAL NOT NULL,
    LONGITUDE       REAL NOT NULL,
    CONSTRAINT COORDINATES_UNIQUE UNIQUE(LATITUDE, LONGITUDE)
);