CREATE TABLE UNALLOCATED_TASK (
    ID              BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    BANK_ID         BIGINT NOT NULL,
    DESIRED_DATE    DATE NOT NULL,
    CONSTRAINT BANK_UNIQUE UNIQUE(BANK_ID),
    FOREIGN KEY (BANK_ID) REFERENCES BANK (ID)
);